version: "3.9"

services:
  shopify_postgres:
    image: postgres:15
    container_name: shopify_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  shopify_backend:
    build: .
    container_name: shopify_backend
    restart: always
    env_file:
      - .env
    expose:
      - "8000"
    depends_on:
      shopify_postgres:
        condition: service_healthy
    command: >
      sh -c "until pg_isready -h shopify_postgres -U ${POSTGRES_USER} -d ${POSTGRES_DB}; do
               echo 'Waiting for Postgres...'; sleep 2; done;
               uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  shopify_nginx:
    image: nginx:alpine
    container_name: shopify_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./certbot-webroot:/var/www/certbot
    depends_on:
      shopify_backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  shopify_certbot:
    image: certbot/certbot
    container_name: shopify_certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./certbot-webroot:/var/www/certbot
    entrypoint: >
      sh -c "trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew --webroot -w /var/www/certbot; done"

volumes:
  postgres_data:
  certbot-etc:
  certbot-var:
